name: Cypress Tests
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # 👈 lets you run manually from GitHub Actions tab
 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
 
      - name: Install dependencies
        run: npm ci
 
      - name: Install Cypress
        run: npx cypress install
 
      - name: Run Cypress tests
        run: npx cypress run --spec cypress/e2e/login-tests.cy.js
        env:
          CYPRESS_baseUrl: https://opensource-demo.orangehrmlive.com
 
      - name: Upload screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
 
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports